package:
  name: carma
  version: 0.8.0

source:
  git_url: https://github.com/RUrlus/carma
  git_tag: v0.8.0

build:
  number: 0

requirements:
  build:
    - git # [win]
    - cmake
    - python
    - {{ compiler('cxx') }}
    - ninja  # [win]
  host:
    - python
    - pip
    - armadillo
    - numpy>=1.24
    - pybind11
  run:
    - python
    - armadillo
    - numpy>=1.24
    - pybind11
