package:
  name: carma
  version: 0.6.7

source:
  git_url: https://github.com/RUrlus/carma
  git_tag: v0.6.7

build:
  number: 0

requirements:
  build:
    - git # [win]
    - make # [unix]
    - cmake
    - {{ compiler('cxx') }} 
    - {{ compiler('fortran') }} # [unix]
  host:
    - python
    - pip
    - armadillo
    - numpy
    - pybind11
  run:
    - python
    - armadillo
    - numpy
    - pybind11
