package:
  name: simcoon
  version: 1.9.6

source:
  git_url: https://github.com/3MAH/simcoon.git
  #git_tag: 1.9.6
  #path: local path for local build

build:
  number: 0
  script_env:
  - CXXFLAGS=-D_LIBCPP_DISABLE_AVAILABILITY

requirements:
  build:
    - git # [win]
    - make # [unix]
    - cmake
    - gtest
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }} # [not win]
    - llvm-openmp  # [osx]
    - libgomp      # [linux]    
  host:
    - armadillo >=12.6
    - carma
    - pybind11
    - python
    - pip
    - setuptools
    - libblas
    - liblapack
    - boost >=1.84
    - ninja
  run:
    - python
    - numpy>=1.26
    - libblas * *accelerate # [osx and arm64]
    - liblapack * *accelerate # [osx and arm64]
    - libblas * *mkl # [x86]
    - liblapack * *mkl # [x86]
    - mkl # [x86]
    - blas * openblas  # Use OpenBLAS for all other platforms  # [not (osx and arm64) and not x86]    
    - lapack * openblas  # Use OpenBLAS for all other platforms  # [not (osx and arm64) and not x86]    
    - boost >=1.84
    - armadillo >=12.6 # [not win]
test:
  imports:
    - simcoon
    - simcoon.simmit
