package:
  name: simcoon
  version: 1.0.0

source:
  git_url: https://github.com/3MAH/simcoon.git
  #git_tag: 1.9.0

build:
  number: 0

requirements:
  build:
    - git # [win]
    - make # [unix]
    - cmake
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }} # [not win]
    - ninja  # [win]
  host:
    - arpack  # [unix]
    - superlu >=5.2.0,<6  # [unix]
    - python
    - numpy>=1.24
    - pip
    - setuptools
    - cgal
    - boost
    - pybind11
    - armadillo
    - carma
  run:
    - arpack  # [unix]
    - superlu >=5.2.0,<6  # [unix]
    - python
    - numpy>=1.24
    - cgal
    - boost
    - pybind11
    - armadillo
    - carma

test:
  imports:
    - simcoon
    - simcoon.simmit
