package:
  name: simcoon
  version: 1.9.5

source:
  git_url: https://github.com/3MAH/simcoon.git
  #git_tag: 1.9.5

build:
  number: 0
  script_env:
  - CXXFLAGS=-D_LIBCPP_DISABLE_AVAILABILITY

requirements:
  build:
    - git # [win]
    - make # [unix]
    - cmake
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }} # [not win]
  host:
    - python
    - {{ pin_compatible('numpy') }}
    - pip
    - setuptools
    - pybind11
    - mkl # [x86]
    - blas # [not win]
    - lapack # [not win]
    - libblas * *netlib # [win]
    - liblapack * *netlib # [win]
    - armadillo >=12.6
    - carma    
    - llvm-openmp # [not x86]
    - ninja
  run:
    # - arpack  # [linux]
    # - superlu >=5.2.0,<6  # [linux]
    - python
    - {{ pin_compatible('numpy') }}
    - blas * accelerate # [osx and arm64]
    - lapack * accelerate # [osx and arm64]
    - libblas * *mkl # [x86]
    - liblapack * *mkl # [x86]
    - mkl # [x86]
    - blas * openblas  # Use OpenBLAS for all other platforms  # [not (osx and arm64) and not x86]    
    - lapack * openblas  # Use OpenBLAS for all other platforms  # [not (osx and arm64) and not x86]    
    - boost
    - libboost
    - pybind11
    - armadillo
    - carma
    - llvm-openmp # [not x86]

test:
  imports:
    - simcoon
    - simcoon.simmit
