package:
  name: simcoon
  version: 1.9.7

source:
  git_url: https://github.com/3MAH/simcoon.git  # [not environ.get('CONDA_BUILD_LOCAL')]
  path: ..  # [environ.get('CONDA_BUILD_LOCAL')]
  #git_tag: 1.9.7  # Uncomment for specific release builds

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  script_env:
    - CXXFLAGS=-D_LIBCPP_DISABLE_AVAILABILITY
    - CONDA_BUILD_LOCAL

requirements:
  build:
    - git # [win]
    - cmake
    - ninja
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }} # [not win]
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
  host:
    - armadillo >=12.6
    - mkl # [x86]
    - blas # [not win]
    - lapack # [not win]
    - libblas * *netlib # [win]
    - liblapack * *netlib # [win]
    - carma
    - pybind11
    - python
    - pip
    - scikit-build-core >=0.11
    - numpy >=2.0
    - libblas
    - liblapack
    - boost >=1.84
  run:
    - python
    - numpy >=2.0
    - libblas * *accelerate # [osx and arm64]
    - liblapack * *accelerate # [osx and arm64]
    - libblas * *mkl # [x86]
    - liblapack * *mkl # [x86]
    - mkl # [x86]
    - blas * openblas  # [not (osx and arm64) and not x86]
    - lapack * openblas  # [not (osx and arm64) and not x86]
    - boost >=1.84
    - armadillo >=12.6 # [not win]

test:
  imports:
    - simcoon
    - simcoon.simmit
