package:
  name: simcoon
  version: 1.0.0

source:
  git_url: https://github.com/3MAH/simcoon.git 
  #git_tag: 1.9.0

build:
  number: 0

requirements:
  build:
    - git # [win]
    - make # [unix]
    - cmake
    - python
    - numpy>=1.22
    - {{ compiler('cxx') }} 
    - {{ compiler('fortran') }} # [unix]
  host:
    - python
    - numpy>=1.22
    - pip
    - cgal
    - boost
    - pybind11
    - armadillo
    - carma
  run:
    - python
    - numpy>=1.22
    - cgal    
    - boost
    - pybind11
    - armadillo    
    - carma

test:
  imports:
    - simcoon
    - simcoon.simmit
