package:
  name: simcoon
  version: 1.9.3

source:
  git_url: https://github.com/3MAH/simcoon.git
  #git_tag: 1.9.0

build:
  number: 0
  script_env:
  - CXXFLAGS=-D_LIBCPP_DISABLE_AVAILABILITY

requirements:
  build:
    - git # [win]
    - make # [unix]
    - cmake
    - python    
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }} # [not win]
  host:
    - arpack  # [linux]
    - superlu >=5.2.0,<6  # [linux]
    - python
    - {{ pin_compatible('numpy') }}
    - pip
    - setuptools
    - boost <=1.84
    - libboost <=1.84
    - gtest
    - pybind11
    - libblas * *openblas # [not win]
    - liblapack * *openblas # [not win]
    - libblas * *netlib # [win]
    - liblapack * *netlib # [win]
    - armadillo
    - carma    
    - llvm-openmp
    - ninja
  run:
    - arpack  # [linux]
    - superlu >=5.2.0,<6  # [linux]
    - python
    - {{ pin_compatible('numpy') }}
    - openblas # [not win]
    - mkl # [win]
    - boost <=1.84
    - libboost <=1.84
    - pybind11
    - armadillo
    - carma
    - llvm-openmp

test:
  imports:
    - simcoon
    - simcoon.simmit
