package:
  name: simcoon
  version: 1.0.0

source:
  git_url: https://github.com/3MAH/simcoon.git

build:
  number: 0

requirements:
  build:
    - git # [win]
    - make # [unix]
    - cmake=3.21
    - {{ compiler('cxx') }} 
    - {{ compiler('fortran') }} # [unix]
  host:
    - python=3.9
    - setuptools
    - pip
    - numpy=1.21
    - cgal
    - boost=1.72
    - armadillo # [unix]
  run:
    - python=3.9
    - boost=1.72

test:
  imports:
    - simcoon
    - simcoon.simmit
