package:
  name: simcoon
  version: 1.0.0

source:
  git_url: https://github.com/3MAH/simcoon.git
build:
  number: 0

requirements:
  build:
    - git # [win]
    - make # [unix]
    - cmake
    - {{ compiler('cxx') }} 
    - {{ compiler('fortran') }} # [unix]
  host:
    - python {{ python }}
    - pip
    - cgal
    - boost
    - armadillo # [unix]
  run:
    - python {{ python }}
    - cgal # [linux]
    - boost

test:
  imports:
    - simcoon
    - simcoon.simmit
