package:
  name: simcoon
  version: 1.9.4

source:
  git_url: https://github.com/3MAH/simcoon.git
  #git_tag: 1.9.0

build:
  number: 0
  script_env:
  - CXXFLAGS=-D_LIBCPP_DISABLE_AVAILABILITY

requirements:
  build:
    - git # [win]
    - make # [unix]
    - cmake
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }} # [not win]
  host:
    # - arpack  # [linux]
    # - superlu >=5.2.0,<6  # [linux]
    - python
    - {{ pin_compatible('numpy') }}
    - pip
    - setuptools
    - boost
    - libboost
    - gtest
    - pybind11
    - libblas * *openblas # [not win]
    - liblapack * *openblas # [not win]
    - libblas * *netlib # [win]
    - liblapack * *netlib # [win]
    - armadillo
    - carma    
    - llvm-openmp # [not x86]
    - mkl # [x86]
    - ninja
  run:
    # - arpack  # [linux]
    # - superlu >=5.2.0,<6  # [linux]
    - python
    - {{ pin_compatible('numpy') }}
    - openblas # [not x86]
    - libblas * *mkl # [x86]
    - liblapack * *mkl # [x86]
    - mkl # [x86]
    - boost
    - libboost
    - pybind11
    - armadillo
    - carma
    - llvm-openmp # [not x86]

test:
  imports:
    - simcoon
    - simcoon.simmit