name: Conda packaging osx

on:
  workflow_dispatch:

jobs:           
  macos:
    name: MacOS
    runs-on: "macos-latest"
    steps:
      - uses: actions/checkout@v4
      
      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          activate-environment: packaging-linux

      - name: Install Dependencies
        shell: bash -l {0}
        run: |
          conda update --all     
          conda clean --all          
          conda install conda-build anaconda-client conda-verify
          conda config --set anaconda_upload no          

      - name: Build Package
        shell: bash -l {0}
        run: |
          conda-build conda.recipe -c set3mah -c conda-forge --no-test --output-folder  .

      - name: Upload to Anaconda
        shell: bash -l {0}
        run: |
          set ANACONDA_API_TOKEN=${{ secrets.ANACONDA_TOKEN }}
          anaconda login --username ${{ secrets.ANACONDA_USERNAME }} --password ${{ secrets.ANACONDA_PASSWORD }}
          anaconda upload osx-arm64/*.tar.bz2 --force
          anaconda upload osx-arm64/*.conda --force
          anaconda logout 
