name: Conda packaging windows

on:
  workflow_dispatch:

jobs:
  windows:
    name: Windows
    runs-on: "windows-latest"
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
      - name: Conda build for Windows
        shell: pwsh
        run: |
          conda update --all        
          conda install conda-build anaconda-client conda-verify
          conda clean --all                    
          conda-build conda.recipe -c set3mah -c conda-forge --no-test --output-folder  .
          anaconda login --username ${{ secrets.ANACONDA_USERNAME }} --password ${{ secrets.ANACONDA_PASSWORD }}
          conda config --set anaconda_upload yes
          anaconda upload win-64/*.tar.bz2 --force
          anaconda logout
