name: Conda packaging linux

on:
  workflow_dispatch:

jobs:        
  Linux:
    name: Linux
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      
      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          activate-environment: packaging-linux

      - name: Install Dependencies
        shell: bash -l {0}
        run: |
          conda update --all        
          conda install conda-build anaconda-client conda-verify

      - name: Build Package
        shell: bash -l {0}
        run: |
          conda-build conda.recipe -c set3mah -c conda-forge --no-test

      - name: Upload to Anaconda
        shell: bash -l {0}
        env:
          ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        run: |
          anaconda login --token $ANACONDA_API_TOKEN
          anaconda upload --user ${{ secrets.ANACONDA_USERNAME }} $(conda-build --output conda.recipe)